### ISSUE TITLE
[NixOS]: Hyprshade doesn't work (can't connect to "/tmp/hypr/*/.socket.sock.) 

### ISSUE THREAD

**Issue by markaacosta** [loqusion/hyprshade#35] opened 2024-05-18 04:42 UTC
See issue here for context: https://github.com/hyprwm/Hyprland/issues/6112

Hyprshade seems broken on NixOS - `hyprshade on` doesn't do anything, other commands (e.g. `hyprshade ls`) produce the erroneous output mentioned in the above issue.

**Comment by loqusion** [comment] 2024-05-18 13:03
The [hyprshade available on nixpkgs](https://search.nixos.org/packages?channel=23.11&show=hyprshade&from=0&size=50&sort=relevance&type=packages&query=hyprshade) is version 0.12.1, the latest stable version is 3.2.1. Try [installing from PyPI](https://github.com/loqusion/hyprshade?tab=readme-ov-file#pypi) and let me know the output of `hyprshade -v on <SHADER>` and `hyprshade -v ls -l`.

**Comment by markaacosta** [comment] 2024-05-18 14:26
I'm seeing the issue on 3.2.1 (I use the 'nix unstable' channel which is ahead of nix 23.11). Here's the output below:

<hr>

### `hyprshade -v on blue-light-filter.glsl.mustache`

> here I pass the path and it looks in the standard `/nix/store/*` and `$HOME/.config/hypr/shaders/` directories:

```
Traceback (most recent call last):
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/bin/.hyprshade-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/__init__.py", line 44, in main
    raise e
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/__init__.py", line 41, in main
    return cli()
           ^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/on.py", line 18, in on
    shader.on()
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/shader/core.py", line 96, in on
    path_ = self._resolve_path()
            ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/shader/core.py", line 114, in _resolve_path
    return self._resolve_path_from_shader_dirs()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/shader/core.py", line 123, in _resolve_path_from_shader_dirs
    raise FileNotFoundError(
FileNotFoundError: Shader 'blue-light-filter.glsl' could not be found in any of the following directories:
	/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/share/hyprshade/shaders
	/home/marka/.config/hypr/shaders

```

### `hyprshade -v on ./blue-light-filter.glsl.mustache`

> here I pass with the explicit leading `./` and it points to the shader in my current directory. It doesn't turn on, despite the shorter output that mentions it is turning on:

```
DEBUG:root:Turning on shader 'blue-light-filter.glsl' at '/home/marka/Downloads/blue-light-filter.glsl.mustache'
```

### `hyprshade -v ls -l`

> output with the '-v' flag:

```
Traceback (most recent call last):
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/shader/hyprctl.py", line 57, in get_screen_shader
    shader_json = json.loads(hyprctl_pipe.stdout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/bin/.hyprshade-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/__init__.py", line 44, in main
    raise e
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/__init__.py", line 41, in main
    return cli()
           ^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a9illw5w19kdzrl312h10hk39w36xx46-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/ls.py", line 75, in ls
    shaders = ShaderWithMeta.get_shaders_list()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/ls.py", line 37, in get_shaders_list
    current = cls._current()
              ^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/cli/ls.py", line 51, in _current
    shader = super().current()
             ^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/shader/core.py", line 106, in current
    path_ = hyprctl.get_screen_shader()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade/shader/hyprctl.py", line 72, in get_screen_shader
    raise RuntimeError(message) from e
RuntimeError: hyprctl returned invalid JSON.
This is likely a bug in Hyprland; go bug Vaxry about it (nicely :)).

[31mstdout[0m:
    Couldn't connect to /tmp/hypr/4cdddcfe466cb21db81af0ac39e51cc15f574da9_1716037622_2056029974/.socket.sock. (3)

[31mstderr[0m:
    <empty>

```

**Comment by markaacosta** [comment] 2024-05-18 14:28
I imagine the PyPi version will work fine - I will try that soon if I can and put the output here

**Comment by loqusion** [comment] 2024-05-18 15:30
There are some weird things going on here that are probably specific to NixOS:

- `blue-light-filter` isn't being found in `$out/share/hyprshade/shaders` (see the [package definition](https://github.com/NixOS/nixpkgs/blob/33d1e753c82ffc557b4a585c77de43d4c922ebb5/pkgs/applications/window-managers/hyprwm/hyprshade/default.nix#L30-L34)), this could indicate an issue with installation
- `hyprctl` is failing to connect to the running Hyprland instance
	- `hyprctl` should really be returning a non-zero exit code and printing errors to stderr so that it can be programmatically determined that there's an error and the output is not just malformed JSON, that's why Hyprshade is conflating the two in its error message

I assume when you're running `hyprshade -v on ./blue-light-filter.glsl.mustache` that you're using [this file](https://github.com/loqusion/hyprshade/blob/d002f6a5cee1260ccc1aa80da8f9a8a65bdc5ef4/shaders/blue-light-filter.glsl.mustache)? If so, it's likely not working because support for shader templates (`.glsl.mustache` files) has not been in any release yet. Try this instead:

```glsl
/*
 * Blue Light Filter
 *
 * Use warmer colors to make the display easier on your eyes.
 *
 * Source: https://github.com/hyprwm/Hyprland/issues/1140#issuecomment-1335128437
 */

precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

/**
 * Color temperature in Kelvin.
 *
 * @min 1000.0
 * @max 40000.0
 */
const float Temperature = 2600.0;

/**
 * Strength of filter.
 *
 * @min 0.0
 * @max 1.0
 */
const float Strength = 1.0;

#define WithQuickAndDirtyLuminancePreservation
const float LuminancePreservationFactor = 1.0;

// function from https://www.shadertoy.com/view/4sc3D7
// valid from 1000 to 40000 K (and additionally 0 for pure full white)
vec3 colorTemperatureToRGB(const in float temperature) {
    // values from: http://blenderartists.org/forum/showthread.php?270332-OSL-Goodness&p=2268693&viewfull=1#post2268693
    mat3 m = (temperature <= 6500.0) ? mat3(vec3(0.0, -2902.1955373783176, -8257.7997278925690),
                                            vec3(0.0, 1669.5803561666639, 2575.2827530017594),
                                            vec3(1.0, 1.3302673723350029, 1.8993753891711275))
                                     : mat3(vec3(1745.0425298314172, 1216.6168361476490, -8257.7997278925690),
                                            vec3(-2666.3474220535695, -2173.1012343082230, 2575.2827530017594),
                                            vec3(0.55995389139931482, 0.70381203140554553, 1.8993753891711275));
    return mix(clamp(vec3(m[0] / (vec3(clamp(temperature, 1000.0, 40000.0)) + m[1]) + m[2]), vec3(0.0), vec3(1.0)),
               vec3(1.0), smoothstep(1000.0, 0.0, temperature));
}

void main() {
    vec4 pixColor = texture2D(tex, v_texcoord);

    // RGB
    vec3 color = vec3(pixColor[0], pixColor[1], pixColor[2]);

#ifdef WithQuickAndDirtyLuminancePreservation
    color *= mix(1.0, dot(color, vec3(0.2126, 0.7152, 0.0722)) / max(dot(color, vec3(0.2126, 0.7152, 0.0722)), 1e-5),
                 LuminancePreservationFactor);
#endif

    color = mix(color, color * colorTemperatureToRGB(Temperature), Strength);

    vec4 outCol = vec4(color, pixColor[3]);

    gl_FragColor = outCol;
}
```

**Comment by loqusion** [comment] 2024-05-18 16:07
Hyprshade 3.2.1 looks for shaders in the following directories: `$HYPRSHADE_SHADERS_DIR`, `~/.config/hyprland/shaders`, `~/.config/hyprshade/shaders`, `<data-dir>/share/hyprshade/shaders` (`<data-dir>` is the return value of [`sysconfig.get_path("data")`](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_path), and is usually `/usr` on linux systems). The code which defines these directories is [here](https://github.com/loqusion/hyprshade/blob/85c636823b7d54d1dba0cf612699f1f6289c1a00/src/hyprshade/shader/core.py#L16-L55).

`<data-dir>/share/hyprshade/shaders` seems not to exist on your system, and judging from the [Nix package definition](https://github.com/NixOS/nixpkgs/blob/33d1e753c82ffc557b4a585c77de43d4c922ebb5/pkgs/applications/window-managers/hyprwm/hyprshade/default.nix#L30-L34) it seems like this is expected, since a wrapper for `hyprshade` is created which sets `$HYPRSHADE_SHADERS_DIR`, presumably as a workaround. But while this directory exists, it seems not to contain `blue-light-filter.glsl` for some reason.

**Comment by markaacosta** [comment] 2024-05-18 19:04
![image](https://github.com/loqusion/hyprshade/assets/20131701/19e84026-ea69-4037-8e8c-9d4e66aa8e4c)

Here's an example of attempting to enable it. Whether I let it use an implicit path or force an explicit one, as long as I pass a non-mustache filter and a valid filter name, it seems it does try to apply it, and there's no error output I can see either. This is true both for filters in the `/nix/store/*` path, and the ~/.config/hyprland/shaders`. Other paths you mentioned too I think. 

So even when the path is valid, though it says it's turning it on, it's just not applying it for some reason. Maybe someone else on NixOS unstable will chime in if they're (probably) experiencing the same thing. If there's other helpful info I can provide you let me know, but for now, that's probably the extent of my helpful knowledge.

**Comment by willswats** [comment] 2024-05-18 19:18
I have the same issue on NixOS with `Hyprland` git (commit `c21a5a934061c248ff1cdd459a74a05b621fb427`), however, on `Hyprland` `v0.39.1` `hyprshade` works fine.

**Comment by loqusion** [comment] 2024-05-18 19:27
Ah, I see now that I was making an assumption which was incorrect. I've updated my previous comments with that in mind.

@markaacosta Could you run `hyprshade on blue-light-filter && hyprctl -j getoption decoration:screen_shader` and paste the output here? That lets me know whether `decoration:screen_shader` is being set. If it's something like `/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/share/hyprshade/shaders/blue-light-filter.glsl`, then there's probably some issue with your version of Hyprland that's not applying the screen shader.

As a side note, it's strange that the error `Couldn't connect to /tmp/hypr/4cdddcfe466cb21db81af0ac39e51cc15f574da9_1716037622_2056029974/.socket.sock` happens with `hyprshade ls` but not with `hyprshade on`, since they're both running `hyprctl` under the hood.

**Comment by markaacosta** [comment] 2024-05-18 19:34
> it's strange that the error Couldn't connect to /tmp/hypr/.../.socket.sock happens with hyprshade ls but not with hyprshade on, since they're both running hyprctl under the hood

very strange, yeah

<hr>

here's the new output:

`hyprshade on blue-light-filter && hyprctl -j getoption decoration:screen_shader`:

```
{"option": "decoration:screen_shader", "str": "[[EMPTY]]", "set": false }

```

**Comment by loqusion** [comment] 2024-05-18 19:40
Hmm, so `hyprshade on blue-light-filter` isn't setting `decoration:screen_shader` then.

Try `hyprctl keyword decoration:screen_shader <path-to-shader>` and then `hyprctl -j getoption decoration:screen_shader` (replace `<path-to-shader>` with the absolute path to `blue-light-filter.glsl`)?

**Comment by markaacosta** [comment] 2024-05-18 19:44
`hyprctl keyword decoration:screen_shader /nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/share/hyprshade/shaders/blue-light-filter.glsl`

> running this applied the filter with no issues

`hyprctl -j getoption decoration:screen_shader`

```
{"option": "decoration:screen_shader", "str": "/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/share/hyprshade/shaders/blue-light-filter.glsl", "set": true }

```

> and now the hyprctl JSON seems fine too

**Comment by loqusion** [comment] 2024-05-18 20:32
Either one of two things is happening here:

1. `hyprshade on blue-light-filter` does not run `hyprctl keyword decoration:screen_shader /nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/share/hyprshade/shaders/blue-light-filter.glsl`
2. `hyprshade on blue-light-filter` _does_ run the above, but runs in a context where the `hyprctl` command fails silently

I doubt 1. is the case, since we can see from the debug output above that Hyprshade is correctly resolving the path to `blue-light-filter.glsl` and I have no reason to believe that the [`subprocess.run()` call](https://github.com/loqusion/hyprshade/blob/85c636823b7d54d1dba0cf612699f1f6289c1a00/src/hyprshade/shader/hyprctl.py#L35-L40) is malformed or that the incorrect parameter is being passed to [`hyprctl.set_screen_shader()`](https://github.com/loqusion/hyprshade/blob/85c636823b7d54d1dba0cf612699f1f6289c1a00/src/hyprshade/shader/core.py#L98). However, I want to completely rule out this possibility.

Could you write the following to `hyprctl.py.patch`:

```patch
--- shader/hyprctl.py	2024-05-18 15:06:54
+++ shader/hyprctl.py.new	2024-05-18 15:07:47
@@ -32,12 +32,13 @@
 
 def set_screen_shader(shader_path: str) -> None:
     try:
-        subprocess.run(
+        result = subprocess.run(
             ["hyprctl", "keyword", "decoration:screen_shader", shader_path],
             capture_output=True,
             check=True,
             encoding="utf-8",
         )
+        print(result.args)
     except subprocess.CalledProcessError as e:
         raise HyprctlError(e) from e
 
```

...then run this (might have to run as root with `sudo`)

```shell
patch -d <hyprshade-root> -i hyprctl.py.patch
```

(Replace `<hyprshade-root>` with `/nix/store/80fjhzmrkpi4zx9x2c8lgf0fxwk23ccp-python3.11-hyprshade-3.2.1/lib/python3.11/site-packages/hyprshade`, which should be where the source code for Hyprshade is located on your system.)

Afterwards, run `hyprshade -v on blue-light-filter` and let me know the output.

**Comment by markaacosta** [comment] 2024-05-18 23:18
Since NixOS is declarative / read-only, I can't apply the patch directly. I'll see if I can manage to apply it using nix tooling then check back.

**Comment by loqusion** [comment] 2024-05-19 15:45
It's ok, I don't think it's necessary for reasons I'll explain soon.

**Comment by loqusion** [comment] 2024-05-19 15:49
> As a side note, it's strange that the error `Couldn't connect to /tmp/hypr/.../.socket.sock` happens with `hyprshade ls` but not with `hyprshade on`, since they're both running `hyprctl` under the hood.

So, it turns out I was completely wrong about this: it's not strange. And the reason is this: the only reason `hyprshade ls` was failing and reporting the error is because it tried to parse the output of `hyprctl` as JSON, whereas `hyprshade on` runs `hyprctl` and only reports an error if the exit code is non-zero... except, the exit code of `hyprctl` is [_not_](https://github.com/hyprwm/Hyprland/blob/47b087950dcfaf6fdda63c4d5f13efda3508a6fb/hyprctl/main.cpp#L122-L125) non-zero if it fails to connect to the Hyprland socket. `hyprctl`'s general method of reporting errors is to print an error message to `stdout`, which makes it difficult to detect every error programatically unless we make assumptions about the formatting of the error message which have no guarantee of remaining correct in the future. (Proper exit code implementation was actually [added a few days ago](https://github.com/hyprwm/Hyprland/commit/3fe5280ce93a7c216f47e8626e69ea015e875395), so at least we won't have to worry about this any more eventually.)

While we have yet to determine with 100% certainty whether `hyprshade on` runs `hyprctl` properly, I think it's safe to assume that it is, and that it's experiencing the same error as with `hyprshade ls` but not reporting it for reasons elaborated on above.

---

Now, that begs the question: why is `hyprctl` failing to connect to the socket? More specifically, why does `hyprctl` succeed in connecting to the socket when run interactively, but not as a subprocess of `hyprshade`?

**Comment by loqusion** [comment] 2024-05-19 16:00
> I have the same issue on NixOS with `Hyprland` git (commit `c21a5a934061c248ff1cdd459a74a05b621fb427`), however, on `Hyprland` `v0.39.1` `hyprshade` (3.2.1) works fine.

Since the error seems not to occur for @willswats in Hyprland v0.39.1, I wonder if the same would also apply for @markaacosta. @markaacosta Would you mind confirming if this is true?

**Comment by loqusion** [comment] 2024-05-19 16:28
By the way, I couldn't reproduce the error on the development version of Hyprland ([`f8857e6`](https://github.com/hyprwm/Hyprland/tree/f8857e6072bd85b95393499688872aaf7f088b5b)) in Arch Linux (btw), so I'm going to assume this error is specific to NixOS until proven otherwise. I've also updated the title to reflect that.

**Comment by markaacosta** [comment] 2024-05-19 16:31
> > I have the same issue on NixOS with `Hyprland` git (commit `c21a5a934061c248ff1cdd459a74a05b621fb427`), however, on `Hyprland` `v0.39.1` `hyprshade` (3.2.1) works fine.
> 
> Since the error seems not to occur for @willswats in Hyprland v0.39.1, I wonder if the same would also apply for @markaacosta. @markaacosta Would you mind confirming if this is true?

I'm building 0.39 right now, I'll let you know

**Comment by markaacosta** [comment] 2024-05-19 17:18
on 0.39 hyprland everything works fine for me too

**Comment by willswats** [comment] 2024-05-19 18:10
I think I figured out whats wrong, the `hyprshade` in nixpkgs is using `Hyprland` `v0.39.1` as that's currently the latest version, and it hasn't been updated probably because of [this issue](https://github.com/hyprwm/Hyprland/issues/5891). To fix this you can override the `Hyprland` package that `hyprshade` uses like so (this is if you are using flakes):

```nix
(pkgs.hyprshade.override {
  hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;
})
```
I don't know if this is the typical behavior for when there is a difference between the `Hyprland` version that `hyprshade` uses, or if this only occurred due to there being a lot of under-the-hood changes in the `Hyprland` `v0.40.0` release.

**Comment by willswats** [comment] 2024-05-19 18:16
Perhaps it's due to this breaking change in Hyprland `v0.40.0`:

- The hyprland logs, sockets, etc. have moved from /tmp/hypr to $XDG_RUNTIME_DIR/hypr.

**Comment by loqusion** [comment] 2024-05-19 19:52
> I think I figured out whats wrong, the `hyprshade` in nixpkgs is using `Hyprland` `v0.39.1` as that's currently the latest version, and it hasn't been updated probably because of [this issue](https://github.com/hyprwm/Hyprland/issues/5891). To fix this you can override the `Hyprland` package that `hyprshade` uses like so (this is if you are using flakes):
> 
> 
> 
> ```nix
> 
> (pkgs.hyprshade.override {
> 
>   hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;
> 
> })
> 
> ```
> 
> I don't know if this is the typical behavior for when there is a difference between the `Hyprland` version that `hyprshade` uses, or if this only occurred due to there being a lot of under-the-hood changes in the `Hyprland` `v0.40.0` release.  

I didn't even think of the possibility that Hyprshade is running the wrong `hyprctl` executable! Bravo, William. Let's hope this fix also works for @markaacosta.

**Comment by markaacosta** [comment] 2024-05-19 20:39
> 
> ```nix
> (pkgs.hyprshade.override {
>   hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;
> })
> ```

I'm on flakes, yeah. Did you add this directly to the `inputs` block of `flake.nix`? Or add it somewhere else?

**Comment by willswats** [comment] 2024-05-19 21:55
> > ```nix
> > (pkgs.hyprshade.override {
> >   hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;
> > })
> > ```
> 
> I'm on flakes, yeah. Did you add this directly to the `inputs` block of `flake.nix`? Or add it somewhere else?

Add it to `environment.systemPackages`:

```nix
{ pkgs, inputs, ... }:

{
  environment.systemPackages = [
    (pkgs.hyprshade.override {
      hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;
    })
  ];
}
```

Or `home.packages` if you are using `home-manager`:

```nix
{ pkgs, inputs, ... }:

{
  home.packages = [
    (pkgs.hyprshade.override {
      hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;
    })
  ];
}
```

And If you haven't done so already, you will also need to add [`@inputs` to the `outputs` part of your flake](https://github.com/willswats/nixos-config/blob/66a05532e34a024f4f1f1e58c28aab7badc0946b/flake.nix#L37), and then [inherit inputs in `specialArgs`](https://github.com/willswats/nixos-config/blob/66a05532e34a024f4f1f1e58c28aab7badc0946b/flake.nix#L107), or in [`extraSpecialArgs` for `home-manager`](https://github.com/willswats/nixos-config/blob/66a05532e34a024f4f1f1e58c28aab7badc0946b/flake.nix#L119C1-L119C23) so that you can access `inputs` as an argument.

**Comment by markaacosta** [comment] 2024-05-19 22:22
@willswats I've got all that other scaffolding and have modularized things pretty well, but I hadn't seen this construct for overriding specific attributes or dependencies for a package. Thanks for the great tip - and @loqusion this also definitely fixed / rolled back hyprshade for me!

**Comment by loqusion** [comment] 2024-05-19 22:43
Great! I'll pin the issue in case it helps anyone else experiencing the same error, and hide some comments to increase visibility of the solution.

**Closed by loqusion** 2024-05-19 22:43 UTC
